
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-09T11:10:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b64596576f83e387642d1d6c4131612b9c19ef20",
 "version": "0.6.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
