
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-13T10:20:54-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "983b9fa7f854922daee318fcb73d31d728421c2a",
 "version": "v1.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
