# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: welog/profile/post_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='welog/profile/post_info.proto',
  package='bigo.pb3',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dwelog/profile/post_info.proto\x12\x08\x62igo.pb3\"\xed\x05\n\x08PostInfo\x12\x0f\n\x07post_id\x18\x01 \x01(\x04\x12\x12\n\nposter_uid\x18\x02 \x01(\x04\x12\x16\n\x0epost_timestamp\x18\x03 \x01(\r\x12\x13\n\x0bvideo_width\x18\x04 \x01(\r\x12\x14\n\x0cvideo_height\x18\x05 \x01(\r\x12\x0b\n\x03\x64ur\x18\x06 \x01(\r\x12\x0c\n\x04\x66lag\x18\x07 \x01(\r\x12\x14\n\x0c\x63ountry_code\x18\x08 \x01(\t\x12\x13\n\x0bvideo_group\x18\t \x01(\x04\x12\x10\n\x08is_carry\x18\n \x01(\x05\x12\x13\n\x0blow_quality\x18\x0b \x01(\r\x12\x14\n\x0c\x63heck_status\x18\x0c \x01(\r\x12\x12\n\nvideo_lang\x18\r \x01(\r\x12\x11\n\tvideo_lat\x18\x0e \x01(\r\x12\x17\n\x0foriginal_poster\x18\x0f \x01(\x04\x12\x12\n\nrec_status\x18\x10 \x01(\r\x12\x14\n\x0creview_level\x18\x11 \x01(\r\x12\x1a\n\x12low_quality_reason\x18\x12 \x01(\x04\x12\x11\n\tpost_type\x18\x13 \x01(\x05\x12\x15\n\rduet_video_id\x18\x14 \x01(\x04\x12\x12\n\nhash_tags2\x18\x16 \x03(\x04\x12\x12\n\nhuman_tags\x18\x17 \x03(\r\x12\x0e\n\x06magics\x18\x18 \x03(\r\x12\x0f\n\x07sticker\x18\x19 \x03(\r\x12\x0e\n\x06musics\x18\x1a \x01(\r\x12\x11\n\tcut_me_id\x18\x1b \x03(\r\x12\x12\n\ntimeout_ts\x18\x1c \x01(\x04\x12\x17\n\x0f\x64\x65tail_share_pv\x18\x1d \x01(\r\x12\x17\n\x0fnew_install_cnt\x18\x1e \x01(\r\x12\x13\n\x0b\x63luster_ids\x18\x1f \x03(\r\x12\x0b\n\x03src\x18  \x01(\r\x12\x14\n\x0cmachine_tags\x18! \x03(\r\x12\x0f\n\x07\x65\x66\x66\x65\x63ts\x18\" \x03(\r\x12\x11\n\thash_tags\x18# \x03(\x04\x12\x0f\n\x07qscores\x18$ \x03(\r\x12\x17\n\x0fmsg_text_length\x18% \x01(\r\x12\x0e\n\x06\x61\x63r_id\x18\' \x01(\r\"r\n\x0bPostCounter\x12\x0f\n\x07post_id\x18\x01 \x01(\x04\x12\x12\n\nplay_count\x18\x02 \x01(\r\x12\x15\n\rcomment_count\x18\x03 \x01(\r\x12\x12\n\nlike_count\x18\x04 \x01(\r\x12\x13\n\x0bshare_count\x18\x05 \x01(\r\"$\n\rPostExtraInfo\x12\x13\n\x0bvideo_group\x18\x01 \x01(\x04\x62\x06proto3')
)




_POSTINFO = _descriptor.Descriptor(
  name='PostInfo',
  full_name='bigo.pb3.PostInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='post_id', full_name='bigo.pb3.PostInfo.post_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='poster_uid', full_name='bigo.pb3.PostInfo.poster_uid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_timestamp', full_name='bigo.pb3.PostInfo.post_timestamp', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_width', full_name='bigo.pb3.PostInfo.video_width', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_height', full_name='bigo.pb3.PostInfo.video_height', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dur', full_name='bigo.pb3.PostInfo.dur', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='bigo.pb3.PostInfo.flag', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country_code', full_name='bigo.pb3.PostInfo.country_code', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_group', full_name='bigo.pb3.PostInfo.video_group', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_carry', full_name='bigo.pb3.PostInfo.is_carry', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low_quality', full_name='bigo.pb3.PostInfo.low_quality', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='check_status', full_name='bigo.pb3.PostInfo.check_status', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_lang', full_name='bigo.pb3.PostInfo.video_lang', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_lat', full_name='bigo.pb3.PostInfo.video_lat', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='original_poster', full_name='bigo.pb3.PostInfo.original_poster', index=14,
      number=15, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rec_status', full_name='bigo.pb3.PostInfo.rec_status', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='review_level', full_name='bigo.pb3.PostInfo.review_level', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low_quality_reason', full_name='bigo.pb3.PostInfo.low_quality_reason', index=17,
      number=18, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_type', full_name='bigo.pb3.PostInfo.post_type', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duet_video_id', full_name='bigo.pb3.PostInfo.duet_video_id', index=19,
      number=20, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash_tags2', full_name='bigo.pb3.PostInfo.hash_tags2', index=20,
      number=22, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='human_tags', full_name='bigo.pb3.PostInfo.human_tags', index=21,
      number=23, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='magics', full_name='bigo.pb3.PostInfo.magics', index=22,
      number=24, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sticker', full_name='bigo.pb3.PostInfo.sticker', index=23,
      number=25, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='musics', full_name='bigo.pb3.PostInfo.musics', index=24,
      number=26, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cut_me_id', full_name='bigo.pb3.PostInfo.cut_me_id', index=25,
      number=27, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout_ts', full_name='bigo.pb3.PostInfo.timeout_ts', index=26,
      number=28, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detail_share_pv', full_name='bigo.pb3.PostInfo.detail_share_pv', index=27,
      number=29, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_install_cnt', full_name='bigo.pb3.PostInfo.new_install_cnt', index=28,
      number=30, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cluster_ids', full_name='bigo.pb3.PostInfo.cluster_ids', index=29,
      number=31, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src', full_name='bigo.pb3.PostInfo.src', index=30,
      number=32, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_tags', full_name='bigo.pb3.PostInfo.machine_tags', index=31,
      number=33, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='effects', full_name='bigo.pb3.PostInfo.effects', index=32,
      number=34, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash_tags', full_name='bigo.pb3.PostInfo.hash_tags', index=33,
      number=35, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qscores', full_name='bigo.pb3.PostInfo.qscores', index=34,
      number=36, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_text_length', full_name='bigo.pb3.PostInfo.msg_text_length', index=35,
      number=37, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acr_id', full_name='bigo.pb3.PostInfo.acr_id', index=36,
      number=39, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=793,
)


_POSTCOUNTER = _descriptor.Descriptor(
  name='PostCounter',
  full_name='bigo.pb3.PostCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='post_id', full_name='bigo.pb3.PostCounter.post_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='play_count', full_name='bigo.pb3.PostCounter.play_count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment_count', full_name='bigo.pb3.PostCounter.comment_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='like_count', full_name='bigo.pb3.PostCounter.like_count', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='share_count', full_name='bigo.pb3.PostCounter.share_count', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=795,
  serialized_end=909,
)


_POSTEXTRAINFO = _descriptor.Descriptor(
  name='PostExtraInfo',
  full_name='bigo.pb3.PostExtraInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_group', full_name='bigo.pb3.PostExtraInfo.video_group', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=911,
  serialized_end=947,
)

DESCRIPTOR.message_types_by_name['PostInfo'] = _POSTINFO
DESCRIPTOR.message_types_by_name['PostCounter'] = _POSTCOUNTER
DESCRIPTOR.message_types_by_name['PostExtraInfo'] = _POSTEXTRAINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PostInfo = _reflection.GeneratedProtocolMessageType('PostInfo', (_message.Message,), dict(
  DESCRIPTOR = _POSTINFO,
  __module__ = 'welog.profile.post_info_pb2'
  # @@protoc_insertion_point(class_scope:bigo.pb3.PostInfo)
  ))
_sym_db.RegisterMessage(PostInfo)

PostCounter = _reflection.GeneratedProtocolMessageType('PostCounter', (_message.Message,), dict(
  DESCRIPTOR = _POSTCOUNTER,
  __module__ = 'welog.profile.post_info_pb2'
  # @@protoc_insertion_point(class_scope:bigo.pb3.PostCounter)
  ))
_sym_db.RegisterMessage(PostCounter)

PostExtraInfo = _reflection.GeneratedProtocolMessageType('PostExtraInfo', (_message.Message,), dict(
  DESCRIPTOR = _POSTEXTRAINFO,
  __module__ = 'welog.profile.post_info_pb2'
  # @@protoc_insertion_point(class_scope:bigo.pb3.PostExtraInfo)
  ))
_sym_db.RegisterMessage(PostExtraInfo)


# @@protoc_insertion_point(module_scope)
