
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-16T00:33:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c811300caa9a156cddcda7a71047fbf8779b4060",
 "version": "0.13.0.post.dev15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
