DOMAIN_AMAZON = 'amazon'
DOMAIN_FLIPKART = 'flipkart'

AMAZON_KEY = "AKIAILPP6CX4JT6HQMXQ"
AMAZON_SECRET = "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"
AMAZON_AFFILIATE_ID = "bestlootdea03-21"
AMAZON_COUNTRY = "IN"

FLIPKART_AFFILIATE_ID = 'mppatelmi'
FLIPKART_AFFILIATE_API_KEY = 'a08b93cd2da74e9fb50f66c03bcf1286'
