# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AttributeFilter(Model):
    """AttributeFilter.

    :param schema_id:
    :type schema_id: str
    :param schema_issuer_did:
    :type schema_issuer_did: str
    :param schema_name:
    :type schema_name: str
    :param schema_version:
    :type schema_version: str
    :param issuer_did:
    :type issuer_did: str
    :param cred_def_id:
    :type cred_def_id: str
    :param attribute_value:
    :type attribute_value: ~credentials.models.AttributeValue
    """

    _attribute_map = {
        'schema_id': {'key': 'schema_id', 'type': 'str'},
        'schema_issuer_did': {'key': 'schema_issuer_did', 'type': 'str'},
        'schema_name': {'key': 'schema_name', 'type': 'str'},
        'schema_version': {'key': 'schema_version', 'type': 'str'},
        'issuer_did': {'key': 'issuer_did', 'type': 'str'},
        'cred_def_id': {'key': 'cred_def_id', 'type': 'str'},
        'attribute_value': {'key': 'attributeValue', 'type': 'AttributeValue'},
    }

    def __init__(self, **kwargs):
        super(AttributeFilter, self).__init__(**kwargs)
        self.schema_id = kwargs.get('schema_id', None)
        self.schema_issuer_did = kwargs.get('schema_issuer_did', None)
        self.schema_name = kwargs.get('schema_name', None)
        self.schema_version = kwargs.get('schema_version', None)
        self.issuer_did = kwargs.get('issuer_did', None)
        self.cred_def_id = kwargs.get('cred_def_id', None)
        self.attribute_value = kwargs.get('attribute_value', None)
