#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['dStorage']

package_data = \
{'': ['*']}

setup(name='dStorage',
      version='0.0.1a0',
      description='these is the constructor of class ',
      author='Leonardo de Araújo Lima',
      author_email='leonardo@asl-sl.com.br',
      url='https://github.com/leo0-07/dStorage',
      packages=packages,
      package_data=package_data,
     )
