# -*- coding: utf-8 -*-

"""
    open_weather_api

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class Clouds(object):

    """Implementation of the 'clouds' model.

    This model contains the cloud information.

    Attributes:
        all (int): This field contains overall stats information

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "all":'all'
    }

    def __init__(self,
                 all=None):
        """Constructor for the Clouds class"""

        # Initialize members of the class
        self.all = all


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        all = dictionary.get('all')

        # Return an object of this model
        return cls(all)


