
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-09T06:44:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "54414a3eeee533b7a9142ad50e3e6597cca4bccf",
 "version": "0.43.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
