
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-11T10:23:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ead7ce0f7f73bacf8253b018cba607e259b0ba4",
 "version": "v0.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
