# Generated by Django 2.2.16 on 2020-12-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoDataImportCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('import_workflow', models.CharField(max_length=64, verbose_name='Import Workflow')),
                ('datafile', models.FileField(upload_to='django-data-import/', verbose_name='Data File')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Add Time')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('parse_success', models.NullBooleanField(verbose_name='Parse Result')),
                ('parse_time', models.DateTimeField(blank=True, null=True, verbose_name='Parse Time')),
                ('parse_error', models.TextField(blank=True, null=True, verbose_name='Parse Error')),
                ('import_success', models.NullBooleanField(verbose_name='Import Result')),
                ('import_time', models.DateTimeField(blank=True, null=True, verbose_name='Import Time')),
                ('import_error', models.TextField(blank=True, null=True, verbose_name='Import Error')),
            ],
            options={
                'verbose_name': 'Django Data Import Case',
                'verbose_name_plural': 'Django Data Import Cases',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='DjangoDataImportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.NullBooleanField(verbose_name='Success')),
                ('info', models.CharField(blank=True, max_length=512, null=True, verbose_name='Item Information')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='Data')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='django_data_import_management.DjangoDataImportCase', verbose_name='Django Data Import Case')),
            ],
        ),
    ]
