# Generated by Django 2.2.16 on 2020-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_data_import_management', '0002_auto_20201210_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangodataimportcase',
            name='import_success',
        ),
        migrations.RemoveField(
            model_name='djangodataimportcase',
            name='parse_success',
        ),
        migrations.AddField(
            model_name='djangodataimportcase',
            name='import_result',
            field=models.IntegerField(blank=True, choices=[(10, 'Success'), (20, 'Failed'), (30, 'Partly Failed')], null=True, verbose_name='Import Result'),
        ),
        migrations.AddField(
            model_name='djangodataimportcase',
            name='parse_result',
            field=models.IntegerField(blank=True, choices=[(10, 'Success'), (20, 'Failed'), (30, 'Partly Failed')], null=True, verbose_name='Parse Result'),
        ),
        migrations.AlterField(
            model_name='djangodataimportitem',
            name='import_success',
            field=models.NullBooleanField(default=None, verbose_name='Import Success'),
        ),
    ]
