
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-16T15:26:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6bcb792bc9e8c3beaa33139881df087db474a151",
 "version": "0.4.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
