# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VerificationDataPolicyCredentialParameters(Model):
    """VerificationDataPolicyCredentialParameters.

    :param verification_data:
    :type verification_data: str
    :param parameters:
    :type parameters:
     list[~wallet.models.VerificationPolicyCredentialParameters]
    """

    _attribute_map = {
        'verification_data': {'key': 'verificationData', 'type': 'str'},
        'parameters': {'key': 'parameters', 'type': '[VerificationPolicyCredentialParameters]'},
    }

    def __init__(self, **kwargs):
        super(VerificationDataPolicyCredentialParameters, self).__init__(**kwargs)
        self.verification_data = kwargs.get('verification_data', None)
        self.parameters = kwargs.get('parameters', None)
