
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-10T18:46:19+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc08661c9a979c371881c85835cd58ec84242b5e",
 "version": "2.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
