
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-12T17:37:24+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b85c9ceab626e1513e46a653e1b8fb175a34e50b",
 "version": "2.0.0rc9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
