# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: welog/profile/video_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='welog/profile/video_info.proto',
  package='bigo.pb3',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1ewelog/profile/video_info.proto\x12\x08\x62igo.pb3\"\xa3\x04\n\tVideoItem\x12\x0f\n\x07post_id\x18\x01 \x01(\x04\x12\x12\n\nposter_uid\x18\x02 \x01(\x04\x12\x11\n\tpost_time\x18\x03 \x01(\r\x12\x11\n\tpost_type\x18\x04 \x01(\r\x12\x14\n\x0c\x63heck_status\x18\x05 \x01(\r\x12\x10\n\x08msg_text\x18\x06 \x01(\t\x12\x11\n\tvideo_url\x18\x07 \x01(\t\x12\x0e\n\x06images\x18\x08 \x03(\t\x12\x12\n\nplay_count\x18\t \x01(\r\x12\x15\n\rcomment_count\x18\n \x01(\r\x12\x12\n\nlike_count\x18\x0b \x01(\r\x12\x13\n\x0bvideo_width\x18\x0c \x01(\r\x12\x14\n\x0cvideo_height\x18\r \x01(\r\x12\x0c\n\x04\x66lag\x18\x0e \x01(\r\x12\x0b\n\x03lng\x18\x0f \x01(\r\x12\x0b\n\x03lat\x18\x10 \x01(\r\x12\x13\n\x0b\x63ountry_ids\x18\x11 \x03(\r\x12\x14\n\x0creview_uname\x18\x12 \x01(\t\x12\x13\n\x0bvideo_group\x18\x13 \x01(\x04\x12\x13\n\x0blow_quality\x18\x64 \x01(\r\x12\x19\n\x11video_source_type\x18i \x01(\x05\x12\x17\n\x0foriginal_poster\x18j \x01(\x03\x12\x11\n\tage_score\x18k \x01(\t\x12\x12\n\nvideo_size\x18l \x01(\x04\x12\x10\n\x08\x64uration\x18m \x01(\r\x12\x19\n\x11low_quality_score\x18n \x01(\x02\x12\x11\n\twm_status\x18o \x01(\r\"\xb5\x02\n\x10VideoInfoESQuery\x12\x0c\n\x04size\x18\x01 \x01(\r\x12\x14\n\x0c\x63heck_status\x18\x02 \x01(\r\x12\x0c\n\x04\x66lag\x18\x03 \x01(\r\x12\x12\n\nsort_field\x18\x04 \x01(\t\x12\x12\n\nsort_order\x18\x05 \x01(\t\x12\x17\n\x0fstart_post_time\x18\x06 \x01(\r\x12\x15\n\rend_post_time\x18\x07 \x01(\r\x12\x13\n\x0bposter_uids\x18\x08 \x03(\t\x12\x16\n\x0einclude_topics\x18\t \x03(\t\x12\x19\n\x11\x65xclude_countries\x18\n \x03(\t\x12\x19\n\x11include_countries\x18\x0b \x03(\t\x12\x19\n\x11include_l1_labels\x18\x0c \x03(\t\x12\x19\n\x11include_l2_labels\x18\r \x03(\tb\x06proto3')
)




_VIDEOITEM = _descriptor.Descriptor(
  name='VideoItem',
  full_name='bigo.pb3.VideoItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='post_id', full_name='bigo.pb3.VideoItem.post_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='poster_uid', full_name='bigo.pb3.VideoItem.poster_uid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_time', full_name='bigo.pb3.VideoItem.post_time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_type', full_name='bigo.pb3.VideoItem.post_type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='check_status', full_name='bigo.pb3.VideoItem.check_status', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_text', full_name='bigo.pb3.VideoItem.msg_text', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_url', full_name='bigo.pb3.VideoItem.video_url', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='bigo.pb3.VideoItem.images', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='play_count', full_name='bigo.pb3.VideoItem.play_count', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment_count', full_name='bigo.pb3.VideoItem.comment_count', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='like_count', full_name='bigo.pb3.VideoItem.like_count', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_width', full_name='bigo.pb3.VideoItem.video_width', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_height', full_name='bigo.pb3.VideoItem.video_height', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='bigo.pb3.VideoItem.flag', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='bigo.pb3.VideoItem.lng', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='bigo.pb3.VideoItem.lat', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country_ids', full_name='bigo.pb3.VideoItem.country_ids', index=16,
      number=17, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='review_uname', full_name='bigo.pb3.VideoItem.review_uname', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_group', full_name='bigo.pb3.VideoItem.video_group', index=18,
      number=19, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low_quality', full_name='bigo.pb3.VideoItem.low_quality', index=19,
      number=100, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_source_type', full_name='bigo.pb3.VideoItem.video_source_type', index=20,
      number=105, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='original_poster', full_name='bigo.pb3.VideoItem.original_poster', index=21,
      number=106, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age_score', full_name='bigo.pb3.VideoItem.age_score', index=22,
      number=107, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_size', full_name='bigo.pb3.VideoItem.video_size', index=23,
      number=108, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='bigo.pb3.VideoItem.duration', index=24,
      number=109, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low_quality_score', full_name='bigo.pb3.VideoItem.low_quality_score', index=25,
      number=110, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wm_status', full_name='bigo.pb3.VideoItem.wm_status', index=26,
      number=111, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=592,
)


_VIDEOINFOESQUERY = _descriptor.Descriptor(
  name='VideoInfoESQuery',
  full_name='bigo.pb3.VideoInfoESQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='bigo.pb3.VideoInfoESQuery.size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='check_status', full_name='bigo.pb3.VideoInfoESQuery.check_status', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='bigo.pb3.VideoInfoESQuery.flag', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort_field', full_name='bigo.pb3.VideoInfoESQuery.sort_field', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort_order', full_name='bigo.pb3.VideoInfoESQuery.sort_order', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_post_time', full_name='bigo.pb3.VideoInfoESQuery.start_post_time', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_post_time', full_name='bigo.pb3.VideoInfoESQuery.end_post_time', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='poster_uids', full_name='bigo.pb3.VideoInfoESQuery.poster_uids', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='include_topics', full_name='bigo.pb3.VideoInfoESQuery.include_topics', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exclude_countries', full_name='bigo.pb3.VideoInfoESQuery.exclude_countries', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='include_countries', full_name='bigo.pb3.VideoInfoESQuery.include_countries', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='include_l1_labels', full_name='bigo.pb3.VideoInfoESQuery.include_l1_labels', index=11,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='include_l2_labels', full_name='bigo.pb3.VideoInfoESQuery.include_l2_labels', index=12,
      number=13, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=904,
)

DESCRIPTOR.message_types_by_name['VideoItem'] = _VIDEOITEM
DESCRIPTOR.message_types_by_name['VideoInfoESQuery'] = _VIDEOINFOESQUERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoItem = _reflection.GeneratedProtocolMessageType('VideoItem', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOITEM,
  __module__ = 'welog.profile.video_info_pb2'
  # @@protoc_insertion_point(class_scope:bigo.pb3.VideoItem)
  ))
_sym_db.RegisterMessage(VideoItem)

VideoInfoESQuery = _reflection.GeneratedProtocolMessageType('VideoInfoESQuery', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOINFOESQUERY,
  __module__ = 'welog.profile.video_info_pb2'
  # @@protoc_insertion_point(class_scope:bigo.pb3.VideoInfoESQuery)
  ))
_sym_db.RegisterMessage(VideoInfoESQuery)


# @@protoc_insertion_point(module_scope)
