
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-14T12:03:49+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "15335c917003cbcae12697863a8b320dd1ac7dc8",
 "version": "0.0.65.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
