# coding: utf-8

"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from foxtail_trainer_api.configuration import Configuration


class Job(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'description': 'str',
        'ml_models': 'list[MLModel]',
        'workers': 'list[Worker]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'ml_models': 'mlModels',
        'workers': 'workers'
    }

    def __init__(self, id=None, name=None, description=None, ml_models=None, workers=None, local_vars_configuration=None):  # noqa: E501
        """Job - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._description = None
        self._ml_models = None
        self._workers = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.description = description
        self.ml_models = ml_models
        self.workers = workers

    @property
    def id(self):
        """Gets the id of this Job.  # noqa: E501


        :return: The id of this Job.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Job.


        :param id: The id of this Job.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Job.  # noqa: E501


        :return: The name of this Job.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Job.


        :param name: The name of this Job.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this Job.  # noqa: E501


        :return: The description of this Job.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Job.


        :param description: The description of this Job.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def ml_models(self):
        """Gets the ml_models of this Job.  # noqa: E501


        :return: The ml_models of this Job.  # noqa: E501
        :rtype: list[MLModel]
        """
        return self._ml_models

    @ml_models.setter
    def ml_models(self, ml_models):
        """Sets the ml_models of this Job.


        :param ml_models: The ml_models of this Job.  # noqa: E501
        :type: list[MLModel]
        """

        self._ml_models = ml_models

    @property
    def workers(self):
        """Gets the workers of this Job.  # noqa: E501


        :return: The workers of this Job.  # noqa: E501
        :rtype: list[Worker]
        """
        return self._workers

    @workers.setter
    def workers(self, workers):
        """Sets the workers of this Job.


        :param workers: The workers of this Job.  # noqa: E501
        :type: list[Worker]
        """

        self._workers = workers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Job):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Job):
            return True

        return self.to_dict() != other.to_dict()
