_build_config = {
    "BUILD_TENSORFLOW_OPS" : "ON" == "ON",
    "BUILD_PYTORCH_OPS" : "ON" == "ON",
    "BUILD_CUDA_MODULE" : "ON" == "ON",
    "BUILD_AZURE_KINECT" : "OFF" == "ON",
    "BUILD_LIBREALSENSE" : "OFF" == "ON",
    "BUILD_SHARED_LIBS" : "OFF" == "ON",
    "BUILD_GUI" : "ON" == "ON",
    "BUILD_RPC_INTERFACE": "ON" == "ON",
    "ENABLE_HEADLESS_RENDERING" : "OFF" == "ON",
    "BUILD_JUPYTER_EXTENSION" : "ON" == "ON",
    "BUNDLE_CLOUDVIEWER_ML" : "ON" == "ON",
    "GLIBCXX_USE_CXX11_ABI" : "OFF" == "ON",
    "CMAKE_BUILD_TYPE" : "Release",
    "CUDA_VERSION" : "10.1",
    "CUDA_GENCODES" : "-gencode arch=compute_61,code=sm_61",
    "Tensorflow_VERSION" : "2.3.0",
    "Pytorch_VERSION" : "1.6.0+cu101",
    "WITH_OPENMP" : "ON" == "ON",
}
