# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dm_env_rpc/v1/extensions/properties.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dm_env_rpc.v1 import dm_env_rpc_pb2 as dm__env__rpc_dot_v1_dot_dm__env__rpc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dm_env_rpc/v1/extensions/properties.proto',
  package='dm_env_rpc.v1.extensions.properties',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)dm_env_rpc/v1/extensions/properties.proto\x12#dm_env_rpc.v1.extensions.properties\x1a\x1e\x64m_env_rpc/v1/dm_env_rpc.proto\"\x8b\x01\n\x0cPropertySpec\x12\'\n\x04spec\x18\x01 \x01(\x0b\x32\x19.dm_env_rpc.v1.TensorSpec\x12\x13\n\x0bis_readable\x18\x02 \x01(\x08\x12\x13\n\x0bis_writable\x18\x03 \x01(\x08\x12\x13\n\x0bis_listable\x18\x04 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"\"\n\x13ListPropertyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"Y\n\x14ListPropertyResponse\x12\x41\n\x06values\x18\x01 \x03(\x0b\x32\x31.dm_env_rpc.v1.extensions.properties.PropertySpec\"\"\n\x13ReadPropertyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"<\n\x14ReadPropertyResponse\x12$\n\x05value\x18\x01 \x01(\x0b\x32\x15.dm_env_rpc.v1.Tensor\"I\n\x14WritePropertyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.dm_env_rpc.v1.Tensor\"\x17\n\x15WritePropertyResponse\"\x97\x02\n\x0fPropertyRequest\x12Q\n\rread_property\x18\x01 \x01(\x0b\x32\x38.dm_env_rpc.v1.extensions.properties.ReadPropertyRequestH\x00\x12S\n\x0ewrite_property\x18\x02 \x01(\x0b\x32\x39.dm_env_rpc.v1.extensions.properties.WritePropertyRequestH\x00\x12Q\n\rlist_property\x18\x03 \x01(\x0b\x32\x38.dm_env_rpc.v1.extensions.properties.ListPropertyRequestH\x00\x42\t\n\x07payload\"\x9b\x02\n\x10PropertyResponse\x12R\n\rread_property\x18\x01 \x01(\x0b\x32\x39.dm_env_rpc.v1.extensions.properties.ReadPropertyResponseH\x00\x12T\n\x0ewrite_property\x18\x02 \x01(\x0b\x32:.dm_env_rpc.v1.extensions.properties.WritePropertyResponseH\x00\x12R\n\rlist_property\x18\x03 \x01(\x0b\x32\x39.dm_env_rpc.v1.extensions.properties.ListPropertyResponseH\x00\x42\t\n\x07payloadb\x06proto3'
  ,
  dependencies=[dm__env__rpc_dot_v1_dot_dm__env__rpc__pb2.DESCRIPTOR,])




_PROPERTYSPEC = _descriptor.Descriptor(
  name='PropertySpec',
  full_name='dm_env_rpc.v1.extensions.properties.PropertySpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='spec', full_name='dm_env_rpc.v1.extensions.properties.PropertySpec.spec', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_readable', full_name='dm_env_rpc.v1.extensions.properties.PropertySpec.is_readable', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_writable', full_name='dm_env_rpc.v1.extensions.properties.PropertySpec.is_writable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_listable', full_name='dm_env_rpc.v1.extensions.properties.PropertySpec.is_listable', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='dm_env_rpc.v1.extensions.properties.PropertySpec.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=254,
)


_LISTPROPERTYREQUEST = _descriptor.Descriptor(
  name='ListPropertyRequest',
  full_name='dm_env_rpc.v1.extensions.properties.ListPropertyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dm_env_rpc.v1.extensions.properties.ListPropertyRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=290,
)


_LISTPROPERTYRESPONSE = _descriptor.Descriptor(
  name='ListPropertyResponse',
  full_name='dm_env_rpc.v1.extensions.properties.ListPropertyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='dm_env_rpc.v1.extensions.properties.ListPropertyResponse.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=381,
)


_READPROPERTYREQUEST = _descriptor.Descriptor(
  name='ReadPropertyRequest',
  full_name='dm_env_rpc.v1.extensions.properties.ReadPropertyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dm_env_rpc.v1.extensions.properties.ReadPropertyRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=417,
)


_READPROPERTYRESPONSE = _descriptor.Descriptor(
  name='ReadPropertyResponse',
  full_name='dm_env_rpc.v1.extensions.properties.ReadPropertyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='dm_env_rpc.v1.extensions.properties.ReadPropertyResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=479,
)


_WRITEPROPERTYREQUEST = _descriptor.Descriptor(
  name='WritePropertyRequest',
  full_name='dm_env_rpc.v1.extensions.properties.WritePropertyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dm_env_rpc.v1.extensions.properties.WritePropertyRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='dm_env_rpc.v1.extensions.properties.WritePropertyRequest.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=554,
)


_WRITEPROPERTYRESPONSE = _descriptor.Descriptor(
  name='WritePropertyResponse',
  full_name='dm_env_rpc.v1.extensions.properties.WritePropertyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=579,
)


_PROPERTYREQUEST = _descriptor.Descriptor(
  name='PropertyRequest',
  full_name='dm_env_rpc.v1.extensions.properties.PropertyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='read_property', full_name='dm_env_rpc.v1.extensions.properties.PropertyRequest.read_property', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='write_property', full_name='dm_env_rpc.v1.extensions.properties.PropertyRequest.write_property', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='list_property', full_name='dm_env_rpc.v1.extensions.properties.PropertyRequest.list_property', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='dm_env_rpc.v1.extensions.properties.PropertyRequest.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=582,
  serialized_end=861,
)


_PROPERTYRESPONSE = _descriptor.Descriptor(
  name='PropertyResponse',
  full_name='dm_env_rpc.v1.extensions.properties.PropertyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='read_property', full_name='dm_env_rpc.v1.extensions.properties.PropertyResponse.read_property', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='write_property', full_name='dm_env_rpc.v1.extensions.properties.PropertyResponse.write_property', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='list_property', full_name='dm_env_rpc.v1.extensions.properties.PropertyResponse.list_property', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='dm_env_rpc.v1.extensions.properties.PropertyResponse.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=864,
  serialized_end=1147,
)

_PROPERTYSPEC.fields_by_name['spec'].message_type = dm__env__rpc_dot_v1_dot_dm__env__rpc__pb2._TENSORSPEC
_LISTPROPERTYRESPONSE.fields_by_name['values'].message_type = _PROPERTYSPEC
_READPROPERTYRESPONSE.fields_by_name['value'].message_type = dm__env__rpc_dot_v1_dot_dm__env__rpc__pb2._TENSOR
_WRITEPROPERTYREQUEST.fields_by_name['value'].message_type = dm__env__rpc_dot_v1_dot_dm__env__rpc__pb2._TENSOR
_PROPERTYREQUEST.fields_by_name['read_property'].message_type = _READPROPERTYREQUEST
_PROPERTYREQUEST.fields_by_name['write_property'].message_type = _WRITEPROPERTYREQUEST
_PROPERTYREQUEST.fields_by_name['list_property'].message_type = _LISTPROPERTYREQUEST
_PROPERTYREQUEST.oneofs_by_name['payload'].fields.append(
  _PROPERTYREQUEST.fields_by_name['read_property'])
_PROPERTYREQUEST.fields_by_name['read_property'].containing_oneof = _PROPERTYREQUEST.oneofs_by_name['payload']
_PROPERTYREQUEST.oneofs_by_name['payload'].fields.append(
  _PROPERTYREQUEST.fields_by_name['write_property'])
_PROPERTYREQUEST.fields_by_name['write_property'].containing_oneof = _PROPERTYREQUEST.oneofs_by_name['payload']
_PROPERTYREQUEST.oneofs_by_name['payload'].fields.append(
  _PROPERTYREQUEST.fields_by_name['list_property'])
_PROPERTYREQUEST.fields_by_name['list_property'].containing_oneof = _PROPERTYREQUEST.oneofs_by_name['payload']
_PROPERTYRESPONSE.fields_by_name['read_property'].message_type = _READPROPERTYRESPONSE
_PROPERTYRESPONSE.fields_by_name['write_property'].message_type = _WRITEPROPERTYRESPONSE
_PROPERTYRESPONSE.fields_by_name['list_property'].message_type = _LISTPROPERTYRESPONSE
_PROPERTYRESPONSE.oneofs_by_name['payload'].fields.append(
  _PROPERTYRESPONSE.fields_by_name['read_property'])
_PROPERTYRESPONSE.fields_by_name['read_property'].containing_oneof = _PROPERTYRESPONSE.oneofs_by_name['payload']
_PROPERTYRESPONSE.oneofs_by_name['payload'].fields.append(
  _PROPERTYRESPONSE.fields_by_name['write_property'])
_PROPERTYRESPONSE.fields_by_name['write_property'].containing_oneof = _PROPERTYRESPONSE.oneofs_by_name['payload']
_PROPERTYRESPONSE.oneofs_by_name['payload'].fields.append(
  _PROPERTYRESPONSE.fields_by_name['list_property'])
_PROPERTYRESPONSE.fields_by_name['list_property'].containing_oneof = _PROPERTYRESPONSE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['PropertySpec'] = _PROPERTYSPEC
DESCRIPTOR.message_types_by_name['ListPropertyRequest'] = _LISTPROPERTYREQUEST
DESCRIPTOR.message_types_by_name['ListPropertyResponse'] = _LISTPROPERTYRESPONSE
DESCRIPTOR.message_types_by_name['ReadPropertyRequest'] = _READPROPERTYREQUEST
DESCRIPTOR.message_types_by_name['ReadPropertyResponse'] = _READPROPERTYRESPONSE
DESCRIPTOR.message_types_by_name['WritePropertyRequest'] = _WRITEPROPERTYREQUEST
DESCRIPTOR.message_types_by_name['WritePropertyResponse'] = _WRITEPROPERTYRESPONSE
DESCRIPTOR.message_types_by_name['PropertyRequest'] = _PROPERTYREQUEST
DESCRIPTOR.message_types_by_name['PropertyResponse'] = _PROPERTYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PropertySpec = _reflection.GeneratedProtocolMessageType('PropertySpec', (_message.Message,), {
  'DESCRIPTOR' : _PROPERTYSPEC,
  '__module__' : 'dm_env_rpc.v1.extensions.properties_pb2'
  # @@protoc_insertion_point(class_scope:dm_env_rpc.v1.extensions.properties.PropertySpec)
  })
_sym_db.RegisterMessage(PropertySpec)

ListPropertyRequest = _reflection.GeneratedProtocolMessageType('ListPropertyRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTPROPERTYREQUEST,
  '__module__' : 'dm_env_rpc.v1.extensions.properties_pb2'
  # @@protoc_insertion_point(class_scope:dm_env_rpc.v1.extensions.properties.ListPropertyRequest)
  })
_sym_db.RegisterMessage(ListPropertyRequest)

ListPropertyResponse = _reflection.GeneratedProtocolMessageType('ListPropertyResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTPROPERTYRESPONSE,
  '__module__' : 'dm_env_rpc.v1.extensions.properties_pb2'
  # @@protoc_insertion_point(class_scope:dm_env_rpc.v1.extensions.properties.ListPropertyResponse)
  })
_sym_db.RegisterMessage(ListPropertyResponse)

ReadPropertyRequest = _reflection.GeneratedProtocolMessageType('ReadPropertyRequest', (_message.Message,), {
  'DESCRIPTOR' : _READPROPERTYREQUEST,
  '__module__' : 'dm_env_rpc.v1.extensions.properties_pb2'
  # @@protoc_insertion_point(class_scope:dm_env_rpc.v1.extensions.properties.ReadPropertyRequest)
  })
_sym_db.RegisterMessage(ReadPropertyRequest)

ReadPropertyResponse = _reflection.GeneratedProtocolMessageType('ReadPropertyResponse', (_message.Message,), {
  'DESCRIPTOR' : _READPROPERTYRESPONSE,
  '__module__' : 'dm_env_rpc.v1.extensions.properties_pb2'
  # @@protoc_insertion_point(class_scope:dm_env_rpc.v1.extensions.properties.ReadPropertyResponse)
  })
_sym_db.RegisterMessage(ReadPropertyResponse)

WritePropertyRequest = _reflection.GeneratedProtocolMessageType('WritePropertyRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEPROPERTYREQUEST,
  '__module__' : 'dm_env_rpc.v1.extensions.properties_pb2'
  # @@protoc_insertion_point(class_scope:dm_env_rpc.v1.extensions.properties.WritePropertyRequest)
  })
_sym_db.RegisterMessage(WritePropertyRequest)

WritePropertyResponse = _reflection.GeneratedProtocolMessageType('WritePropertyResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITEPROPERTYRESPONSE,
  '__module__' : 'dm_env_rpc.v1.extensions.properties_pb2'
  # @@protoc_insertion_point(class_scope:dm_env_rpc.v1.extensions.properties.WritePropertyResponse)
  })
_sym_db.RegisterMessage(WritePropertyResponse)

PropertyRequest = _reflection.GeneratedProtocolMessageType('PropertyRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROPERTYREQUEST,
  '__module__' : 'dm_env_rpc.v1.extensions.properties_pb2'
  # @@protoc_insertion_point(class_scope:dm_env_rpc.v1.extensions.properties.PropertyRequest)
  })
_sym_db.RegisterMessage(PropertyRequest)

PropertyResponse = _reflection.GeneratedProtocolMessageType('PropertyResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROPERTYRESPONSE,
  '__module__' : 'dm_env_rpc.v1.extensions.properties_pb2'
  # @@protoc_insertion_point(class_scope:dm_env_rpc.v1.extensions.properties.PropertyResponse)
  })
_sym_db.RegisterMessage(PropertyResponse)


# @@protoc_insertion_point(module_scope)
