
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-17T21:41:19+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c6aac9cf84943f5452d31577e43f0f6f2f3a7d1",
 "version": "0.0.68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
