# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2020-12-08 15:37:36.825196
__version__ = '3.0.7'