
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-15T10:29:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "67df64116f7d32283712a20be3ddd8565343032d",
 "version": "2.0.39.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
