
# This file is automatically generated during the generation of setup.py
# Copyright 2020, Adorad
author = 'Jason Dsouza'
author_email = 'jasmcaus@gmail.com'
version = '1.0.0'
full_version = '1.0.0'
git_version = 'Unknown'
release = True
contributors = ['Jason Dsouza <jasmcaus@gmail.com>']
homepage = 'https://github.com/jasmcaus/adorad'
