# Generated by Django 3.1.1 on 2020-09-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octet', '0002_blobreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='blobreference',
            name='labels',
            field=models.JSONField(db_column='labels', default=dict, verbose_name='Labels'),
        ),
    ]
