
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-17T05:35:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "eadc34270c8b1f23adf14ad68e31aa3cf99916df",
 "version": "2.0.39.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
