# Generated by Django 3.0.3 on 2020-12-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_tlmswmsentdetails_wms_ent_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tlmswmsentdetails',
            options={'managed': False, 'verbose_name': '入库计划明细', 'verbose_name_plural': '入库计划明细'},
        ),
    ]
