
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-14T10:41:37+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "56260e06982d08b0850085d8bd2bc6211b26c626",
 "version": "0.0.64"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
