
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-15T00:00:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9c79defe23cf504a6f1e3a77f71e50aee19a25b",
 "version": "0.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
