
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-10T08:11:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "85479a28515ef867d1f1e444fb3fe75a035d7a70",
 "version": "v0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
