# Generated by Django 3.0.3 on 2020-12-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0006_auto_20201203_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tlmswmsentdirect',
            options={'managed': False, 'verbose_name': '委托入库指令', 'verbose_name_plural': '委托入库指令'},
        ),
    ]
