
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-17T03:57:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "45873ce7a4dd14aca0d5dd6c93d27108f411b965",
 "version": "2.0.39.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
