# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/compute_fabric.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layer_client.api import ids_pb2 as api_dot_ids__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/entity/compute_fabric.proto',
  package='api',
  syntax='proto3',
  serialized_options=b'\n\rcom.layer.apiP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1f\x61pi/entity/compute_fabric.proto\x12\x03\x61pi\x1a\rapi/ids.proto\"\xd0\x01\n\rComputeFabric\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.api.ComputeFabricId\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x36\n\rresource_type\x18\x04 \x01(\x0e\x32\x1f.api.ComputeFabric.ResourceType\"W\n\x0cResourceType\x12\x19\n\x15RESOURCE_TYPE_INVALID\x10\x00\x12\x15\n\x11RESOURCE_TYPE_CPU\x10\x01\x12\x15\n\x11RESOURCE_TYPE_GPU\x10\x02\x42\x11\n\rcom.layer.apiP\x01\x62\x06proto3'
  ,
  dependencies=[api_dot_ids__pb2.DESCRIPTOR,])



_COMPUTEFABRIC_RESOURCETYPE = _descriptor.EnumDescriptor(
  name='ResourceType',
  full_name='api.ComputeFabric.ResourceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESOURCE_TYPE_INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESOURCE_TYPE_CPU', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESOURCE_TYPE_GPU', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=177,
  serialized_end=264,
)
_sym_db.RegisterEnumDescriptor(_COMPUTEFABRIC_RESOURCETYPE)


_COMPUTEFABRIC = _descriptor.Descriptor(
  name='ComputeFabric',
  full_name='api.ComputeFabric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.ComputeFabric.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='api.ComputeFabric.name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource_type', full_name='api.ComputeFabric.resource_type', index=2,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPUTEFABRIC_RESOURCETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=264,
)

_COMPUTEFABRIC.fields_by_name['id'].message_type = api_dot_ids__pb2._COMPUTEFABRICID
_COMPUTEFABRIC.fields_by_name['resource_type'].enum_type = _COMPUTEFABRIC_RESOURCETYPE
_COMPUTEFABRIC_RESOURCETYPE.containing_type = _COMPUTEFABRIC
DESCRIPTOR.message_types_by_name['ComputeFabric'] = _COMPUTEFABRIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputeFabric = _reflection.GeneratedProtocolMessageType('ComputeFabric', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTEFABRIC,
  '__module__' : 'api.entity.compute_fabric_pb2'
  # @@protoc_insertion_point(class_scope:api.ComputeFabric)
  })
_sym_db.RegisterMessage(ComputeFabric)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
