# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layer_client.api import ids_pb2 as api_dot_ids__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/entity/model.proto',
  package='api',
  syntax='proto3',
  serialized_options=b'\n\rcom.layer.apiP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x61pi/entity/model.proto\x12\x03\x61pi\x1a\rapi/ids.proto\"\x80\x08\n\x05Model\x12\x18\n\x02id\x18\x01 \x01(\x0b\x32\x0c.api.ModelId\x12/\n\x11\x63ompute_fabric_id\x18\x02 \x01(\x0b\x32\x14.api.ComputeFabricId\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12&\n\x06\x66lavor\x18\x06 \x01(\x0e\x32\x16.api.Model.ModelFlavor\x12$\n\x06owners\x18\x07 \x01(\x0b\x32\x14.api.Model.OwnerList\x12(\n\x0bversion_ids\x18\x08 \x03(\x0b\x32\x13.api.ModelVersionId\x12.\n\rreview_status\x18\t \x01(\x0e\x32\x17.api.Model.ReviewStatus\x12!\n\rparent_app_id\x18\n \x01(\x0b\x32\n.api.AppId\x12+\n\x10\x64\x65\x66\x61ult_train_id\x18\x0b \x01(\x0b\x32\x11.api.ModelTrainId\x12\x14\n\x0c\x64\x61te_created\x18\x0c \x01(\x03\x12\"\n\rcreated_by_id\x18\r \x01(\x0b\x32\x0b.api.UserId\x12,\n\x0forganization_id\x18\x0e \x01(\x0b\x32\x13.api.OrganizationId\x1aK\n\tOwnerList\x12\x1d\n\x08user_ids\x18\x01 \x03(\x0b\x32\x0b.api.UserId\x12\x1f\n\tgroup_ids\x18\x02 \x03(\x0b\x32\x0c.api.GroupId\"\x9b\x01\n\x0cReviewStatus\x12\x19\n\x15REVIEW_STATUS_INVALID\x10\x00\x12\x19\n\x15REVIEW_STATUS_PENDING\x10\x01\x12\x1b\n\x17REVIEW_STATUS_IN_REVIEW\x10\x02\x12\x1a\n\x16REVIEW_STATUS_APPROVED\x10\x03\x12\x1c\n\x18REVIEW_STATUS_UNAPPROVED\x10\x04\"\xbd\x02\n\x0bModelFlavor\x12\x18\n\x14MODEL_FLAVOR_INVALID\x10\x00\x12\x17\n\x13MODEL_FLAVOR_PYFUNC\x10\x01\x12\x14\n\x10MODEL_FLAVOR_H2O\x10\x02\x12\x16\n\x12MODEL_FLAVOR_KERAS\x10\x03\x12\x18\n\x14MODEL_FLAVOR_PYTORCH\x10\x04\x12\x18\n\x14MODEL_FLAVOR_SKLEARN\x10\x05\x12\x16\n\x12MODEL_FLAVOR_SPARK\x10\x06\x12\x1b\n\x17MODEL_FLAVOR_TENSORFLOW\x10\x07\x12\x18\n\x14MODEL_FLAVOR_XGBOOST\x10\x08\x12\x16\n\x12MODEL_FLAVOR_SPACY\x10\t\x12\x17\n\x13MODEL_FLAVOR_FASTAI\x10\n\x12\x19\n\x15MODEL_FLAVOR_LIGHTGBM\x10\x0b\x42\x11\n\rcom.layer.apiP\x01\x62\x06proto3'
  ,
  dependencies=[api_dot_ids__pb2.DESCRIPTOR,])



_MODEL_REVIEWSTATUS = _descriptor.EnumDescriptor(
  name='ReviewStatus',
  full_name='api.Model.ReviewStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REVIEW_STATUS_INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVIEW_STATUS_PENDING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVIEW_STATUS_IN_REVIEW', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVIEW_STATUS_APPROVED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVIEW_STATUS_UNAPPROVED', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=596,
  serialized_end=751,
)
_sym_db.RegisterEnumDescriptor(_MODEL_REVIEWSTATUS)

_MODEL_MODELFLAVOR = _descriptor.EnumDescriptor(
  name='ModelFlavor',
  full_name='api.Model.ModelFlavor',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_PYFUNC', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_H2O', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_KERAS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_PYTORCH', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_SKLEARN', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_SPARK', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_TENSORFLOW', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_XGBOOST', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_SPACY', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_FASTAI', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_FLAVOR_LIGHTGBM', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=754,
  serialized_end=1071,
)
_sym_db.RegisterEnumDescriptor(_MODEL_MODELFLAVOR)


_MODEL_OWNERLIST = _descriptor.Descriptor(
  name='OwnerList',
  full_name='api.Model.OwnerList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_ids', full_name='api.Model.OwnerList.user_ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='group_ids', full_name='api.Model.OwnerList.group_ids', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=518,
  serialized_end=593,
)

_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='api.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.Model.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compute_fabric_id', full_name='api.Model.compute_fabric_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='api.Model.name', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='api.Model.description', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flavor', full_name='api.Model.flavor', index=4,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owners', full_name='api.Model.owners', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version_ids', full_name='api.Model.version_ids', index=6,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='review_status', full_name='api.Model.review_status', index=7,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parent_app_id', full_name='api.Model.parent_app_id', index=8,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='default_train_id', full_name='api.Model.default_train_id', index=9,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_created', full_name='api.Model.date_created', index=10,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_by_id', full_name='api.Model.created_by_id', index=11,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organization_id', full_name='api.Model.organization_id', index=12,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MODEL_OWNERLIST, ],
  enum_types=[
    _MODEL_REVIEWSTATUS,
    _MODEL_MODELFLAVOR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=1071,
)

_MODEL_OWNERLIST.fields_by_name['user_ids'].message_type = api_dot_ids__pb2._USERID
_MODEL_OWNERLIST.fields_by_name['group_ids'].message_type = api_dot_ids__pb2._GROUPID
_MODEL_OWNERLIST.containing_type = _MODEL
_MODEL.fields_by_name['id'].message_type = api_dot_ids__pb2._MODELID
_MODEL.fields_by_name['compute_fabric_id'].message_type = api_dot_ids__pb2._COMPUTEFABRICID
_MODEL.fields_by_name['flavor'].enum_type = _MODEL_MODELFLAVOR
_MODEL.fields_by_name['owners'].message_type = _MODEL_OWNERLIST
_MODEL.fields_by_name['version_ids'].message_type = api_dot_ids__pb2._MODELVERSIONID
_MODEL.fields_by_name['review_status'].enum_type = _MODEL_REVIEWSTATUS
_MODEL.fields_by_name['parent_app_id'].message_type = api_dot_ids__pb2._APPID
_MODEL.fields_by_name['default_train_id'].message_type = api_dot_ids__pb2._MODELTRAINID
_MODEL.fields_by_name['created_by_id'].message_type = api_dot_ids__pb2._USERID
_MODEL.fields_by_name['organization_id'].message_type = api_dot_ids__pb2._ORGANIZATIONID
_MODEL_REVIEWSTATUS.containing_type = _MODEL
_MODEL_MODELFLAVOR.containing_type = _MODEL
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {

  'OwnerList' : _reflection.GeneratedProtocolMessageType('OwnerList', (_message.Message,), {
    'DESCRIPTOR' : _MODEL_OWNERLIST,
    '__module__' : 'api.entity.model_pb2'
    # @@protoc_insertion_point(class_scope:api.Model.OwnerList)
    })
  ,
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'api.entity.model_pb2'
  # @@protoc_insertion_point(class_scope:api.Model)
  })
_sym_db.RegisterMessage(Model)
_sym_db.RegisterMessage(Model.OwnerList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
