# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flexlogger/automation/proto/FlexLoggerApplication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flexlogger.automation.proto import Identifiers_pb2 as flexlogger_dot_automation_dot_proto_dot_Identifiers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='flexlogger/automation/proto/FlexLoggerApplication.proto',
  package='national_instruments.flex_logger.automation.protocols',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n7flexlogger/automation/proto/FlexLoggerApplication.proto\x12\x35national_instruments.flex_logger.automation.protocols\x1a-flexlogger/automation/proto/Identifiers.proto\"*\n\x12OpenProjectRequest\x12\x14\n\x0cproject_path\x18\x01 \x01(\t\"p\n\x13OpenProjectResponse\x12Y\n\x07project\x18\x01 \x01(\x0b\x32H.national_instruments.diagram_sdk.automation.protocols.ProjectIdentifier\"\x19\n\x17GetActiveProjectRequest\"\x97\x01\n\x18GetActiveProjectResponse\x12 \n\x18\x61\x63tive_project_available\x18\x01 \x01(\x08\x12Y\n\x07project\x18\x02 \x01(\x0b\x32H.national_instruments.diagram_sdk.automation.protocols.ProjectIdentifier2\xf8\x02\n\x15\x46lexLoggerApplication\x12\xa6\x01\n\x0bOpenProject\x12I.national_instruments.flex_logger.automation.protocols.OpenProjectRequest\x1aJ.national_instruments.flex_logger.automation.protocols.OpenProjectResponse\"\x00\x12\xb5\x01\n\x10GetActiveProject\x12N.national_instruments.flex_logger.automation.protocols.GetActiveProjectRequest\x1aO.national_instruments.flex_logger.automation.protocols.GetActiveProjectResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[flexlogger_dot_automation_dot_proto_dot_Identifiers__pb2.DESCRIPTOR,])




_OPENPROJECTREQUEST = _descriptor.Descriptor(
  name='OpenProjectRequest',
  full_name='national_instruments.flex_logger.automation.protocols.OpenProjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_path', full_name='national_instruments.flex_logger.automation.protocols.OpenProjectRequest.project_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=203,
)


_OPENPROJECTRESPONSE = _descriptor.Descriptor(
  name='OpenProjectResponse',
  full_name='national_instruments.flex_logger.automation.protocols.OpenProjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='national_instruments.flex_logger.automation.protocols.OpenProjectResponse.project', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=317,
)


_GETACTIVEPROJECTREQUEST = _descriptor.Descriptor(
  name='GetActiveProjectRequest',
  full_name='national_instruments.flex_logger.automation.protocols.GetActiveProjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=344,
)


_GETACTIVEPROJECTRESPONSE = _descriptor.Descriptor(
  name='GetActiveProjectResponse',
  full_name='national_instruments.flex_logger.automation.protocols.GetActiveProjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='active_project_available', full_name='national_instruments.flex_logger.automation.protocols.GetActiveProjectResponse.active_project_available', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project', full_name='national_instruments.flex_logger.automation.protocols.GetActiveProjectResponse.project', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=498,
)

_OPENPROJECTRESPONSE.fields_by_name['project'].message_type = flexlogger_dot_automation_dot_proto_dot_Identifiers__pb2._PROJECTIDENTIFIER
_GETACTIVEPROJECTRESPONSE.fields_by_name['project'].message_type = flexlogger_dot_automation_dot_proto_dot_Identifiers__pb2._PROJECTIDENTIFIER
DESCRIPTOR.message_types_by_name['OpenProjectRequest'] = _OPENPROJECTREQUEST
DESCRIPTOR.message_types_by_name['OpenProjectResponse'] = _OPENPROJECTRESPONSE
DESCRIPTOR.message_types_by_name['GetActiveProjectRequest'] = _GETACTIVEPROJECTREQUEST
DESCRIPTOR.message_types_by_name['GetActiveProjectResponse'] = _GETACTIVEPROJECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpenProjectRequest = _reflection.GeneratedProtocolMessageType('OpenProjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPENPROJECTREQUEST,
  '__module__' : 'flexlogger.automation.proto.FlexLoggerApplication_pb2'
  # @@protoc_insertion_point(class_scope:national_instruments.flex_logger.automation.protocols.OpenProjectRequest)
  })
_sym_db.RegisterMessage(OpenProjectRequest)

OpenProjectResponse = _reflection.GeneratedProtocolMessageType('OpenProjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPENPROJECTRESPONSE,
  '__module__' : 'flexlogger.automation.proto.FlexLoggerApplication_pb2'
  # @@protoc_insertion_point(class_scope:national_instruments.flex_logger.automation.protocols.OpenProjectResponse)
  })
_sym_db.RegisterMessage(OpenProjectResponse)

GetActiveProjectRequest = _reflection.GeneratedProtocolMessageType('GetActiveProjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETACTIVEPROJECTREQUEST,
  '__module__' : 'flexlogger.automation.proto.FlexLoggerApplication_pb2'
  # @@protoc_insertion_point(class_scope:national_instruments.flex_logger.automation.protocols.GetActiveProjectRequest)
  })
_sym_db.RegisterMessage(GetActiveProjectRequest)

GetActiveProjectResponse = _reflection.GeneratedProtocolMessageType('GetActiveProjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETACTIVEPROJECTRESPONSE,
  '__module__' : 'flexlogger.automation.proto.FlexLoggerApplication_pb2'
  # @@protoc_insertion_point(class_scope:national_instruments.flex_logger.automation.protocols.GetActiveProjectResponse)
  })
_sym_db.RegisterMessage(GetActiveProjectResponse)



_FLEXLOGGERAPPLICATION = _descriptor.ServiceDescriptor(
  name='FlexLoggerApplication',
  full_name='national_instruments.flex_logger.automation.protocols.FlexLoggerApplication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=501,
  serialized_end=877,
  methods=[
  _descriptor.MethodDescriptor(
    name='OpenProject',
    full_name='national_instruments.flex_logger.automation.protocols.FlexLoggerApplication.OpenProject',
    index=0,
    containing_service=None,
    input_type=_OPENPROJECTREQUEST,
    output_type=_OPENPROJECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetActiveProject',
    full_name='national_instruments.flex_logger.automation.protocols.FlexLoggerApplication.GetActiveProject',
    index=1,
    containing_service=None,
    input_type=_GETACTIVEPROJECTREQUEST,
    output_type=_GETACTIVEPROJECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FLEXLOGGERAPPLICATION)

DESCRIPTOR.services_by_name['FlexLoggerApplication'] = _FLEXLOGGERAPPLICATION

# @@protoc_insertion_point(module_scope)
