
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-09T09:42:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c13fa1f2c15bf809f924ba1ad760c0dae3f2aa24",
 "version": "1.9.91"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
