
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='labelstream',
    version='0.0.1',
    python_requires='>=3.8',
    packages=["labelstream"],
    package_dir={"": "."},
    package_data={},
    install_requires=['click'],
    extras_require={"dev": ["jupyter"]},
    entry_points={
            'console_scripts': [
                'labelstream = labelstream.labelstream:main'
            ]
    },
)
