
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-11T20:48:00+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b1288386c600e89050c8cabaed60fa7278106f9",
 "version": "2.0.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
