
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-14T22:08:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a66829d5fa405a9cfdd0945672dea1433663ce0f",
 "version": "0.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
