
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-15T00:32:22+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "69201abb52ee74ecac59c3ae27235f3b80537da4",
 "version": "2.4.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
