
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9333577c5453f33d2698965ecab4e66d3f4f5e23",
 "version": "0.26.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
