# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indigo/features/action_feature.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='indigo/features/action_feature.proto',
  package='bigo.indigo.features',
  syntax='proto3',
  serialized_options=_b('\370\001\001'),
  serialized_pb=_b('\n$indigo/features/action_feature.proto\x12\x14\x62igo.indigo.features\"\xfd\x02\n\x13OriginActionFeature\x12\x18\n\x10update_timestamp\x18\x01 \x01(\x04\x12\x12\n\ndispatched\x18\x02 \x01(\x04\x12\x11\n\tdisplayed\x18\x03 \x01(\x04\x12\x0f\n\x07\x63licked\x18\x04 \x01(\x04\x12\x0c\n\x04play\x18\x05 \x01(\x04\x12\x10\n\x08\x66ollowed\x18\x06 \x01(\x04\x12\x0c\n\x04like\x18\x07 \x01(\x04\x12\x0f\n\x07\x63omment\x18\x08 \x01(\x04\x12\x12\n\ndownloaded\x18\n \x01(\x04\x12\x0f\n\x07\x63ontact\x18\x14 \x01(\x04\x12\r\n\x05story\x18\x15 \x01(\x04\x12\x13\n\x0bplay_second\x18\x0b \x01(\x04\x12\x16\n\x0e\x63omplete_count\x18\x0c \x01(\x04\x12\x10\n\x08replayed\x18\r \x01(\x04\x12\x16\n\x0estay_view_time\x18\x0e \x01(\x04\x12\x1e\n\x16valid_staty_view_times\x18\x0f \x01(\x04\x12\x13\n\x0b\x63lickedList\x18\x12 \x01(\x04\x12\x15\n\rdisplayedList\x18\x13 \x01(\x04\"\xe0\x02\n\x11OriginActionQueue\x12@\n\rminutes_queue\x18\x01 \x03(\x0b\x32).bigo.indigo.features.OriginActionFeature\x12>\n\x0bhours_queue\x18\x02 \x03(\x0b\x32).bigo.indigo.features.OriginActionFeature\x12=\n\ndays_queue\x18\x03 \x03(\x0b\x32).bigo.indigo.features.OriginActionFeature\x12\x46\n\x13raw_decayed_feature\x18\x04 \x01(\x0b\x32).bigo.indigo.features.OriginActionFeature\x12\x42\n\x0f\x64\x65\x63\x61yed_feature\x18\x05 \x01(\x0b\x32).bigo.indigo.features.OriginActionFeature\"\xeb\x02\n\x16OriginActionMultiQueue\x12\x42\n\x11\x61\x63tions_universal\x18\x01 \x01(\x0b\x32\'.bigo.indigo.features.OriginActionQueue\x12?\n\x0e\x61\x63tions_in_hot\x18\x02 \x01(\x0b\x32\'.bigo.indigo.features.OriginActionQueue\x12\x42\n\x11\x61\x63tions_in_detail\x18\x03 \x01(\x0b\x32\'.bigo.indigo.features.OriginActionQueue\x12\x42\n\x11\x61\x63tions_in_follow\x18\x04 \x01(\x0b\x32\'.bigo.indigo.features.OriginActionQueue\x12\x44\n\x13\x61\x63tions_in_personal\x18\x05 \x01(\x0b\x32\'.bigo.indigo.features.OriginActionQueueB\x03\xf8\x01\x01\x62\x06proto3')
)




_ORIGINACTIONFEATURE = _descriptor.Descriptor(
  name='OriginActionFeature',
  full_name='bigo.indigo.features.OriginActionFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='update_timestamp', full_name='bigo.indigo.features.OriginActionFeature.update_timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dispatched', full_name='bigo.indigo.features.OriginActionFeature.dispatched', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='displayed', full_name='bigo.indigo.features.OriginActionFeature.displayed', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clicked', full_name='bigo.indigo.features.OriginActionFeature.clicked', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='play', full_name='bigo.indigo.features.OriginActionFeature.play', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='followed', full_name='bigo.indigo.features.OriginActionFeature.followed', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='like', full_name='bigo.indigo.features.OriginActionFeature.like', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='bigo.indigo.features.OriginActionFeature.comment', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='downloaded', full_name='bigo.indigo.features.OriginActionFeature.downloaded', index=8,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contact', full_name='bigo.indigo.features.OriginActionFeature.contact', index=9,
      number=20, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='story', full_name='bigo.indigo.features.OriginActionFeature.story', index=10,
      number=21, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='play_second', full_name='bigo.indigo.features.OriginActionFeature.play_second', index=11,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='complete_count', full_name='bigo.indigo.features.OriginActionFeature.complete_count', index=12,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replayed', full_name='bigo.indigo.features.OriginActionFeature.replayed', index=13,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stay_view_time', full_name='bigo.indigo.features.OriginActionFeature.stay_view_time', index=14,
      number=14, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_staty_view_times', full_name='bigo.indigo.features.OriginActionFeature.valid_staty_view_times', index=15,
      number=15, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clickedList', full_name='bigo.indigo.features.OriginActionFeature.clickedList', index=16,
      number=18, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='displayedList', full_name='bigo.indigo.features.OriginActionFeature.displayedList', index=17,
      number=19, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=444,
)


_ORIGINACTIONQUEUE = _descriptor.Descriptor(
  name='OriginActionQueue',
  full_name='bigo.indigo.features.OriginActionQueue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minutes_queue', full_name='bigo.indigo.features.OriginActionQueue.minutes_queue', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hours_queue', full_name='bigo.indigo.features.OriginActionQueue.hours_queue', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='days_queue', full_name='bigo.indigo.features.OriginActionQueue.days_queue', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_decayed_feature', full_name='bigo.indigo.features.OriginActionQueue.raw_decayed_feature', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decayed_feature', full_name='bigo.indigo.features.OriginActionQueue.decayed_feature', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=799,
)


_ORIGINACTIONMULTIQUEUE = _descriptor.Descriptor(
  name='OriginActionMultiQueue',
  full_name='bigo.indigo.features.OriginActionMultiQueue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actions_universal', full_name='bigo.indigo.features.OriginActionMultiQueue.actions_universal', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions_in_hot', full_name='bigo.indigo.features.OriginActionMultiQueue.actions_in_hot', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions_in_detail', full_name='bigo.indigo.features.OriginActionMultiQueue.actions_in_detail', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions_in_follow', full_name='bigo.indigo.features.OriginActionMultiQueue.actions_in_follow', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions_in_personal', full_name='bigo.indigo.features.OriginActionMultiQueue.actions_in_personal', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=802,
  serialized_end=1165,
)

_ORIGINACTIONQUEUE.fields_by_name['minutes_queue'].message_type = _ORIGINACTIONFEATURE
_ORIGINACTIONQUEUE.fields_by_name['hours_queue'].message_type = _ORIGINACTIONFEATURE
_ORIGINACTIONQUEUE.fields_by_name['days_queue'].message_type = _ORIGINACTIONFEATURE
_ORIGINACTIONQUEUE.fields_by_name['raw_decayed_feature'].message_type = _ORIGINACTIONFEATURE
_ORIGINACTIONQUEUE.fields_by_name['decayed_feature'].message_type = _ORIGINACTIONFEATURE
_ORIGINACTIONMULTIQUEUE.fields_by_name['actions_universal'].message_type = _ORIGINACTIONQUEUE
_ORIGINACTIONMULTIQUEUE.fields_by_name['actions_in_hot'].message_type = _ORIGINACTIONQUEUE
_ORIGINACTIONMULTIQUEUE.fields_by_name['actions_in_detail'].message_type = _ORIGINACTIONQUEUE
_ORIGINACTIONMULTIQUEUE.fields_by_name['actions_in_follow'].message_type = _ORIGINACTIONQUEUE
_ORIGINACTIONMULTIQUEUE.fields_by_name['actions_in_personal'].message_type = _ORIGINACTIONQUEUE
DESCRIPTOR.message_types_by_name['OriginActionFeature'] = _ORIGINACTIONFEATURE
DESCRIPTOR.message_types_by_name['OriginActionQueue'] = _ORIGINACTIONQUEUE
DESCRIPTOR.message_types_by_name['OriginActionMultiQueue'] = _ORIGINACTIONMULTIQUEUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OriginActionFeature = _reflection.GeneratedProtocolMessageType('OriginActionFeature', (_message.Message,), dict(
  DESCRIPTOR = _ORIGINACTIONFEATURE,
  __module__ = 'indigo.features.action_feature_pb2'
  # @@protoc_insertion_point(class_scope:bigo.indigo.features.OriginActionFeature)
  ))
_sym_db.RegisterMessage(OriginActionFeature)

OriginActionQueue = _reflection.GeneratedProtocolMessageType('OriginActionQueue', (_message.Message,), dict(
  DESCRIPTOR = _ORIGINACTIONQUEUE,
  __module__ = 'indigo.features.action_feature_pb2'
  # @@protoc_insertion_point(class_scope:bigo.indigo.features.OriginActionQueue)
  ))
_sym_db.RegisterMessage(OriginActionQueue)

OriginActionMultiQueue = _reflection.GeneratedProtocolMessageType('OriginActionMultiQueue', (_message.Message,), dict(
  DESCRIPTOR = _ORIGINACTIONMULTIQUEUE,
  __module__ = 'indigo.features.action_feature_pb2'
  # @@protoc_insertion_point(class_scope:bigo.indigo.features.OriginActionMultiQueue)
  ))
_sym_db.RegisterMessage(OriginActionMultiQueue)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
