
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-15T16:31:05-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9976a8d152b2b48222d147cc57e9a296196d7ec5",
 "version": "4.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
