
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-15T19:11:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc9c3dec96394f21814506e0d857590a674a20bf",
 "version": "0.1.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
