# -*- coding: utf-8 -*-

"""
    open_weather_api

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class UNITSEnum(object):

    """Implementation of the 'UNITS' enum.

    Defined the units sent in request

    Attributes:
        STANDARD: This is standard unit
        METRIC: This is metric unit
        IMPERIAL: This is imperial unit

    """

    STANDARD = 'standard'

    METRIC = 'metric'

    IMPERIAL = 'imperial'

