# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/service/featureengine/feature_engine_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layer_client.api.entity import dataset_pb2 as api_dot_entity_dot_dataset__pb2
from layer_client.api.entity import dataset_build_pb2 as api_dot_entity_dot_dataset__build__pb2
from layer_client.api.entity import dataset_version_pb2 as api_dot_entity_dot_dataset__version__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/service/featureengine/feature_engine_api.proto',
  package='api',
  syntax='proto3',
  serialized_options=b'\n\rcom.layer.apiB\025FeatureEngineApiProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2api/service/featureengine/feature_engine_api.proto\x12\x03\x61pi\x1a\x18\x61pi/entity/dataset.proto\x1a\x1e\x61pi/entity/dataset_build.proto\x1a api/entity/dataset_version.proto\"\x1c\n\x1a\x42uildAllFeatureSetsRequest\"-\n\x1b\x42uildAllFeatureSetsResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"(\n\x14\x42uildFeaturesRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\t\"~\n\x15\x42uildFeaturesResponse\x12\x1d\n\x07\x64\x61taset\x18\x01 \x01(\x0b\x32\x0c.api.Dataset\x12$\n\x07version\x18\x02 \x01(\x0b\x32\x13.api.DatasetVersion\x12 \n\x05\x62uild\x18\x03 \x01(\x0b\x32\x11.api.DatasetBuild2\xb4\x01\n\x10\x46\x65\x61tureEngineAPI\x12X\n\x13\x42uildAllFeatureSets\x12\x1f.api.BuildAllFeatureSetsRequest\x1a .api.BuildAllFeatureSetsResponse\x12\x46\n\rBuildFeatures\x12\x19.api.BuildFeaturesRequest\x1a\x1a.api.BuildFeaturesResponseB(\n\rcom.layer.apiB\x15\x46\x65\x61tureEngineApiProtoP\x01\x62\x06proto3'
  ,
  dependencies=[api_dot_entity_dot_dataset__pb2.DESCRIPTOR,api_dot_entity_dot_dataset__build__pb2.DESCRIPTOR,api_dot_entity_dot_dataset__version__pb2.DESCRIPTOR,])




_BUILDALLFEATURESETSREQUEST = _descriptor.Descriptor(
  name='BuildAllFeatureSetsRequest',
  full_name='api.BuildAllFeatureSetsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=179,
)


_BUILDALLFEATURESETSRESPONSE = _descriptor.Descriptor(
  name='BuildAllFeatureSetsResponse',
  full_name='api.BuildAllFeatureSetsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='api.BuildAllFeatureSetsResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=226,
)


_BUILDFEATURESREQUEST = _descriptor.Descriptor(
  name='BuildFeaturesRequest',
  full_name='api.BuildFeaturesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='api.BuildFeaturesRequest.features', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=268,
)


_BUILDFEATURESRESPONSE = _descriptor.Descriptor(
  name='BuildFeaturesResponse',
  full_name='api.BuildFeaturesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset', full_name='api.BuildFeaturesResponse.dataset', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='api.BuildFeaturesResponse.version', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build', full_name='api.BuildFeaturesResponse.build', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=396,
)

_BUILDFEATURESRESPONSE.fields_by_name['dataset'].message_type = api_dot_entity_dot_dataset__pb2._DATASET
_BUILDFEATURESRESPONSE.fields_by_name['version'].message_type = api_dot_entity_dot_dataset__version__pb2._DATASETVERSION
_BUILDFEATURESRESPONSE.fields_by_name['build'].message_type = api_dot_entity_dot_dataset__build__pb2._DATASETBUILD
DESCRIPTOR.message_types_by_name['BuildAllFeatureSetsRequest'] = _BUILDALLFEATURESETSREQUEST
DESCRIPTOR.message_types_by_name['BuildAllFeatureSetsResponse'] = _BUILDALLFEATURESETSRESPONSE
DESCRIPTOR.message_types_by_name['BuildFeaturesRequest'] = _BUILDFEATURESREQUEST
DESCRIPTOR.message_types_by_name['BuildFeaturesResponse'] = _BUILDFEATURESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildAllFeatureSetsRequest = _reflection.GeneratedProtocolMessageType('BuildAllFeatureSetsRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUILDALLFEATURESETSREQUEST,
  '__module__' : 'api.service.featureengine.feature_engine_api_pb2'
  # @@protoc_insertion_point(class_scope:api.BuildAllFeatureSetsRequest)
  })
_sym_db.RegisterMessage(BuildAllFeatureSetsRequest)

BuildAllFeatureSetsResponse = _reflection.GeneratedProtocolMessageType('BuildAllFeatureSetsResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUILDALLFEATURESETSRESPONSE,
  '__module__' : 'api.service.featureengine.feature_engine_api_pb2'
  # @@protoc_insertion_point(class_scope:api.BuildAllFeatureSetsResponse)
  })
_sym_db.RegisterMessage(BuildAllFeatureSetsResponse)

BuildFeaturesRequest = _reflection.GeneratedProtocolMessageType('BuildFeaturesRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUILDFEATURESREQUEST,
  '__module__' : 'api.service.featureengine.feature_engine_api_pb2'
  # @@protoc_insertion_point(class_scope:api.BuildFeaturesRequest)
  })
_sym_db.RegisterMessage(BuildFeaturesRequest)

BuildFeaturesResponse = _reflection.GeneratedProtocolMessageType('BuildFeaturesResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUILDFEATURESRESPONSE,
  '__module__' : 'api.service.featureengine.feature_engine_api_pb2'
  # @@protoc_insertion_point(class_scope:api.BuildFeaturesResponse)
  })
_sym_db.RegisterMessage(BuildFeaturesResponse)


DESCRIPTOR._options = None

_FEATUREENGINEAPI = _descriptor.ServiceDescriptor(
  name='FeatureEngineAPI',
  full_name='api.FeatureEngineAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=399,
  serialized_end=579,
  methods=[
  _descriptor.MethodDescriptor(
    name='BuildAllFeatureSets',
    full_name='api.FeatureEngineAPI.BuildAllFeatureSets',
    index=0,
    containing_service=None,
    input_type=_BUILDALLFEATURESETSREQUEST,
    output_type=_BUILDALLFEATURESETSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BuildFeatures',
    full_name='api.FeatureEngineAPI.BuildFeatures',
    index=1,
    containing_service=None,
    input_type=_BUILDFEATURESREQUEST,
    output_type=_BUILDFEATURESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEATUREENGINEAPI)

DESCRIPTOR.services_by_name['FeatureEngineAPI'] = _FEATUREENGINEAPI

# @@protoc_insertion_point(module_scope)
