
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-12T11:04:14-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "944df2fb3bac1acc5451e3ad594c50a96f5de8a8",
 "version": "v0.2.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
